apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: test
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 7.2.0
    helm:
      values: |
        ## MinIO(R) Gateway configuration
        nameOverride: "minio-gateway"
        global:
          minio:
            existingSecret: azuresecret
        auth:
          rootUser: "minio"
          rootPassword: "minio123"
        gateway:
          enabled: true
          type: azure
          replicaCount: 1
          auth:
            azure:
              storageAccountNameExistingSecret: "azuresecret"
              storageAccountNameExistingSecretKey: "azure-storage-account-name"
              storageAccountKeyExistingSecret: "azuresecret"
              storageAccountKeyExistingSecretKey: "azure-storage-account-key"
        image:
          registry: docker.io
          repository: bitnami/minio
          tag: 2021.5.27-debian-10-r8
        podLabels:
          aadpodidbinding: velero
        # initContainers:
        # - name: your-image-name
        #   image: your-image
        #   imagePullPolicy: Always
        #   ports:
        #     - name: portname
        #       containerPort: 1234
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

